remote_theme: botmedia/minimal

title: "Ďakujeme dobrovoľníkom"
description: "Zoznam dobrovoľníkov ktorí pomáhali pri tvorbe covid.chat"

github:
  is_project_page: false
  
# google_analytics_key: UA-129653402-1
